[project]
name = 'blockchain-based-micromobility-platform'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.rental-and-usage-contract]
path = 'contracts/rental-and-usage-contract.clar'
clarity_version = 3
epoch = 'latest'

[contracts.vehicle-registry]
path = 'contracts/vehicle-registry.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
